### ISSUE TITLE
color highlight codeblock

### ISSUE THREAD

**Issue by knguyen0105** [getmicah/getmicah.github.io#4]
Great theme. Exactly what I'm looking for. Thank you for making it public.

Is it possible to enable color highlighting for code block? Right now, code blocks are monocolor (green on black). Thanks.

**Comment by knguyen0105** [comment]
Nevermind. I got it.

**Comment by getmicah** [comment]
For anybody else wondering, Jekyll automatically assigns different classes to different blocks of code so all you have to do is create css classes or find some online.
